Global:
  model_name: dx_plate_det
  use_gpu: true
  epoch_num: 100
  print_batch_step: 10
  save_model_dir: ./output/dx_plate_det
  save_epoch_step: 10
  eval_batch_step: [0, 2000]
  pretrained_model: null
  checkpoints: null
  distributed: false
  seed: 1024
  use_ema: false
  show_eval_progress: true
Architecture:
  model_family: yolo
  task: detect
  algorithm: yolov8
  yaml_file: pytorchx/cfg/models/v8/yolov8.yaml
  scale: n
  in_channels: 3
  Head:
    num_classes: 1
    reg_max: 1
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 1
  regularizer:
    name: L2
    factor: 0.0005
Loss:
  name: DetLoss
  topk: 10
  alpha: 1.0
  beta: 6.0
  cls_gain: 0.5
  box_gain: 7.5
Metric:
  name: DetMetric
  main_indicator: mAP50-95
PostProcess:
  name: DetPostProcess
  conf_thres: 0.25
  iou_thres: 0.7
  strides: [8, 16, 32]
Train:
  dataset:
    name: DetDataset
    data_dir: datasets/dx_det
    label_file_list: [datasets/dx_det/train.txt]
    kpt_shape: null
    transform:
      image_size: 640
  loader:
    batch_size_per_card: 8
    shuffle: true
    drop_last: false
    num_workers: 4
    prefetch_factor: 4
Eval:
  dataset:
    name: DetDataset
    data_dir: datasets/dx_det
    label_file_list: [datasets/dx_det/val.txt]
    kpt_shape: null
    transform:
      image_size: 640
  loader:
    batch_size_per_card: 8
    shuffle: false
    drop_last: false
    num_workers: 0
    prefetch_factor: 4
