Global:
  model_name: parity_pkg_seg
  use_gpu: true
  epoch_num: 100
  print_batch_step: 10
  save_model_dir: ./output/parity_pkg_seg
  save_epoch_step: 10
  eval_batch_step: [0, 2000]
  pretrained_model: null
  checkpoints: null
  distributed: false
  seed: 1024
  use_ema: true
  ema_decay: 0.9999
  ema_decay_type: exponential
  amp: true
  show_eval_progress: true
Architecture:
  model_family: yolo
  task: segment
  algorithm: yolo11-seg
  yaml_file: torchkiln/cfg/models/11/yolo11-seg.yaml
  scale: n
  in_channels: 3
  Head:
    num_classes: 1
    reg_max: 16
Optimizer:
  name: SGD
  momentum: 0.937
  nbs: 64
  lr:
    name: Linear
    learning_rate: 0.01
    lrf: 0.01
    warmup_epoch: 3
    warmup_bias_lr: 0.1
    warmup_momentum: 0.8
  regularizer:
    name: L2
    factor: 0.0005
Loss:
  name: SegLoss
  topk: 10
  alpha: 0.5
  beta: 6.0
  cls_gain: 0.5
  box_gain: 7.5
Metric:
  name: SegMetric
  main_indicator: mask_mAP50-95
PostProcess:
  name: SegPostProcess
  conf_thres: 0.001
  iou_thres: 0.7
  strides: [8, 16, 32]
Train:
  dataset:
    name: SegDataset
    data_dir: G:/_ds
    label_file_list: [G:/_ds/train_sub.txt]
    kpt_shape: null
    augment:
      mosaic: 0.0
      hsv: {p: 1.0, hgain: 0.015, sgain: 0.7, vgain: 0.4}
      affine: {degrees: 0.0, translate: 0.1, scale: 0.5, shear: 0.0, perspective: 0.0}
      fliplr: 0.5
    transform:
      image_size: 256
      mask_stride: 4
  loader:
    batch_size_per_card: 8
    shuffle: true
    drop_last: false
    num_workers: 4
    prefetch_factor: 4
Eval:
  dataset:
    name: SegDataset
    data_dir: G:/_ds
    label_file_list: [G:/_ds/val_sub.txt]
    kpt_shape: null
    transform:
      image_size: 256
      mask_stride: 4
  loader:
    batch_size_per_card: 8
    shuffle: false
    drop_last: false
    num_workers: 0
    prefetch_factor: 4
