Global:
  model_name: yolov9c_g
  use_gpu: true
  epoch_num: 100
  print_batch_step: 10
  save_model_dir: ./output/yolov9c_g
  save_epoch_step: 10
  eval_batch_step: [0, 2000]
  pretrained_model: null
  checkpoints: null
  distributed: false
  seed: 1024
  use_ema: true
  ema_decay: 0.9999
  ema_decay_type: exponential
  show_eval_progress: true
Architecture:
  model_family: yolo
  task: detect
  algorithm: yolov9c
  yaml_file: pytorchx/cfg/models/v9/yolov9c.yaml
  scale: n
  in_channels: 3
  Head:
    num_classes: 2
    reg_max: 1
Optimizer:
  name: SGD
  momentum: 0.937
  nbs: 64
  lr:
    name: Linear
    learning_rate: 0.01
    lrf: 0.01
    warmup_epoch: 3
    warmup_bias_lr: 0.1
    warmup_momentum: 0.8
  regularizer:
    name: L2
    factor: 0.0005
Loss:
  name: DetLoss
  topk: 10
  alpha: 0.5
  beta: 6.0
  cls_gain: 0.5
  box_gain: 7.5
Metric:
  name: DetMetric
  main_indicator: mAP50-95
PostProcess:
  name: DetPostProcess
  conf_thres: 0.001
  iou_thres: 0.7
  strides: [8, 16, 32]
Train:
  dataset:
    name: DetDataset
    data_dir: datasets/det_demo
    label_file_list: [datasets/det_demo/train.txt]
    kpt_shape: null
    transform:
      image_size: 320
  loader:
    batch_size_per_card: 8
    shuffle: true
    drop_last: false
    num_workers: 4
    prefetch_factor: 4
Eval:
  dataset:
    name: DetDataset
    data_dir: datasets/det_demo
    label_file_list: [datasets/det_demo/val.txt]
    kpt_shape: null
    transform:
      image_size: 320
  loader:
    batch_size_per_card: 8
    shuffle: false
    drop_last: false
    num_workers: 0
    prefetch_factor: 4
