Global:
  model_name: yolo11-obb_dota128
  use_gpu: true
  epoch_num: 50
  print_batch_step: 10
  save_model_dir: ./output/yolo11-obb_dota128
  save_epoch_step: 10
  eval_batch_step: [0, 2000]
  pretrained_model: null
  checkpoints: null
  distributed: false
  seed: 1024
  use_ema: true
  ema_decay: 0.9998
  ema_decay_type: threshold
  show_eval_progress: true
Architecture:
  model_family: yolo
  task: obb
  algorithm: yolo11-obb
  yaml_file: pytorchx/cfg/models/11/yolo11-obb.yaml
  scale: n
  in_channels: 3
  Head:
    num_classes: 15
    reg_max: 16
Optimizer:
  name: SGD
  momentum: 0.937
  nbs: 64
  lr:
    name: Linear
    learning_rate: 0.01
    lrf: 0.01
    warmup_epoch: 3
    warmup_bias_lr: 0.1
    warmup_momentum: 0.8
  regularizer:
    name: L2
    factor: 0.0005
Loss:
  name: ObbLoss
  topk: 10
  alpha: 0.5
  beta: 6.0
  cls_gain: 0.5
  box_gain: 7.5
Metric:
  name: DetMetric
  box_format: xywhr
  main_indicator: mAP50-95
PostProcess:
  name: DetPostProcess
  box_type: xywhr
  reg_layout: upstream
  conf_thres: 0.001
  iou_thres: 0.7
  strides: [8, 16, 32]
Train:
  dataset:
    name: DetDataset
    data_dir: datasets/dota128
    label_file_list: [datasets/dota128/train.txt]
    box_format: xywhr
    names:
    - plane
    - ship
    - storage-tank
    - baseball-diamond
    - tennis-court
    - swimming-pool
    - ground-track-field
    - harbor
    - bridge
    - large-vehicle
    - small-vehicle
    - helicopter
    - roundabout
    - soccer-ball-field
    - basketball-court
    transform:
      image_size: 1024
    augment:
      mosaic: 1.0
      mosaic9: 0.0
      mixup: 0.0
      copy_paste: 0.0
      close_mosaic: 10
      multi_scale: 0.0
      hsv: {p: 1.0, hgain: 0.015, sgain: 0.7, vgain: 0.4}
      affine: {degrees: 0.0, translate: 0.1, scale: 0.5, shear: 0.0, perspective: 0.0}
      fliplr: 0.5
      flipud: 0.0
  loader:
    batch_size_per_card: 8
    shuffle: true
    drop_last: false
    num_workers: 4
    prefetch_factor: 4
Eval:
  dataset:
    name: DetDataset
    data_dir: datasets/dota128
    label_file_list: [datasets/dota128/val.txt]
    box_format: xywhr
    names:
    - plane
    - ship
    - storage-tank
    - baseball-diamond
    - tennis-court
    - swimming-pool
    - ground-track-field
    - harbor
    - bridge
    - large-vehicle
    - small-vehicle
    - helicopter
    - roundabout
    - soccer-ball-field
    - basketball-court
    transform:
      image_size: 1024
  loader:
    batch_size_per_card: 8
    shuffle: false
    drop_last: false
    num_workers: 0
    prefetch_factor: 4
